### ISSUE TITLE
Is your system based on PixelExperience_13 or LineageOS_20.0?

### ISSUE THREAD

**Issue by fun1355** [TheNoFace/local_manifests#1]
I watched your patch in device/oneplus/dumpling, it renamed from `lineageos` to `aosp`. So your system based on PixelExperience. 
1. Why you add lineage_sdk? there are too many conflicts about 'org.lineageos.xxx'.  
The Answer : 
"android_lineage-sdk is needed to build OnePlusPocketMode"
 BUT, there are a lot of error. 

2. and hardware/oneplus/KeyHandler/AndroidManifest.xml relies lots of lineageos Class. 
Too many error/warnings....

**Comment by fun1355** [comment]
for example,
/bin/rm -rf out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/gen/aapt2/R && out/host/linux-x86/bin/aapt2 link -o out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/package-res.apk --no-static-lib-packages --manifest out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/manifest_fixer/AndroidManifest.xml  --min-sdk-version 33 --target-sdk-version 33 --version-code 33 --version-name  13 -I out/soong/.intermediates/frameworks/base/core/res/framework-res/android_common/package-res.apk --product nosdcard -c en_US,en_US,af_ZA,am_ET,ar_EG,ar_XB,as_IN,az_AZ,be_BY,bg_BG,bn_BD,bs_BA,ca_ES,cs_CZ,da_DK,de_DE,el_GR,en_AU,en_CA,en_GB,en_IN,en_XA,es_ES,es_US,et_EE,eu_ES,fa_IR,fi_FI,fr_CA,fr_FR,gl_ES,gu_IN,hi_IN,hr_HR,hu_HU,hy_AM,in_ID,is_IS,it_IT,iw_IL,ja_JP,ka_GE,kk_KZ,km_KH,kn_IN,ko_KR,ky_KG,lo_LA,lt_LT,lv_LV,mk_MK,ml_IN,mn_MN,mr_IN,ms_MY,my_MM,nb_NO,ne_NP,nl_NL,or_IN,pa_IN,pl_PL,pt_BR,pt_PT,ro_RO,ru_RU,si_LK,sk_SK,sl_SI,sq_AL,sr_Latn_RS,sr_RS,sv_SE,sw_TZ,ta_IN,te_IN,th_TH,tl_PH,tr_TR,uk_UA,ur_PK,uz_UZ,vi_VN,zh_CN,zh_HK,zh_TW,zu_ZA,en_XC,normal --preferred-density xxhdpi --java out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/gen/aapt2/R --proguard out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/gen/proguard.options --output-text-symbols out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/R.txt @out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/aapt2/res.list && out/host/linux-x86/bin/soong_zip -write_if_changed -jar -o out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/gen/android/R.srcjar -C out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/gen/aapt2/R -D out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/gen/aapt2/R &&out/host/linux-x86/bin/extract_jar_packages -i out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/gen/android/R.srcjar -o out/soong/.intermediates/hardware/oneplus/KeyHandler/KeyHandler/android_common/extra_packages --prefix '--extra-packages '

**Comment by TheNoFace** [comment]
This manifests is for building PE13 for dumpling, thus base repositories are by PixelExperience 13. Also, device configs are just copies of LineageOS configs with some minor fixes to make the build system work. Lineage SDK is needed since device configs are derived from Lineage.

OnePlusPocketMode is dropped due to build errors, and I have no issues regarding hardware/oneplus/KeyHandler. Are you sure you're using my device repository?

**Comment by fun1355** [comment]
Sorry, I have fixed the Keyhander error. by change "org.lineageos.setings.resources" to "org.pixelexperience.settings.resources". thanks all the same. I mistaked deleting the log before, sorry. I have tried "org.aosp.settings.resources", of courser failed....
